stillversion: '3.9'
services:
  backend:
    build: ./backend
    container_name: creditcard-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: creditcard-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  mongo:
    image: mongo:6.0
    container_name: creditcard-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
